development:
  webapp_url: http://localhost:3001
test:
  webapp_url: http://localhost:3001
production:
  webapp_url: <%= ENV["WEBAPP_URL"] %>
  smtp_settings:
    address: 'smtp.sendgrid.net'
    port: 25
    user_name: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    authentication: 'plain'
    enable_starttls_auto: true